apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-gateway
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
