FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /collector ./cmd/collector

FROM alpine:3.20
COPY --from=build /collector /collector
ENTRYPOINT ["/collector"]
