FROM golang:1.23-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /mq ./cmd/mq

FROM alpine:3.20
RUN mkdir -p /data
COPY --from=build /mq /mq
ENTRYPOINT ["/mq"]
