FROM golang:1.23-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /streamer ./cmd/streamer

FROM alpine:3.20
COPY --from=build /streamer /streamer
COPY data/dcgm_metrics.csv /data/dcgm_metrics.csv
ENTRYPOINT ["/streamer"]
